services:
  - type: web
    name: telegram-expense-bot
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn webhook_app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SPREADSHEET_ID
        sync: false
      - key: WORKSHEET_NAME
        value: Sheet1
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: BASE_URL
        sync: false
